export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const FETCHING_LOGIN = "FETCHING_LOGIN";

export const FETCH_TIMEATTEND = "FETCH_TIMEATTEND";
export const ACTION_CHECKIN = "ACTION_CHECKIN";
export const ACTION_CHECKOUT = "ACTION_CHECKOUT";
export const ACTION_CONFIRMCHECK = "ACTION_CONFIRMCHECK";
export const ACTION_SWITCHLOCATION = "ACTION_SWITCHLOCATION";
export const ACTION_LOGOUT = "ACTION_LOGOUT";

export const ACTION_VERIFYTOKEN = "ACTION_VERIFYTOKEN";
export const ACTION_EXPIRETOKEN = "ACTION_EXPIRETOKEN";

export const ACTION_CANCELCHECK = "ACTION_CANCELCHECK";

export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";

export const URL_WS_USER = "https://portal.moj.go.th/ws/user.php/";
export const URL_WS_ATTEND = "https://portal.moj.go.th/ws/attend.php/";